#Use store bought breads and rolls as default

#Create query words to search through a recipe list to link it to unit_weights
unit_weights_query <- readRDS("./data-raw/unit_weights2.Rds") %>% select(-c(grams_per_unit, unit_enhet, reference)) %>% unique() %>% #Only keep names, not units
  mutate(Ingredients = str_replace_all(Ingredients, ',', '')) %>%

  #First two words contain the most important information to identify the ingredients
  mutate(first_word = str_extract(Ingredients, '^\\w+'),
         temp = str_extract(Ingredients, '^\\w+\\s\\w+')) %>%
  mutate(second_word = str_remove(temp, '^\\w+\\s')) %>%
  select(-temp) %>% unique() %>%
  replace_na(list(second_word = '\\')) %>%

  #Clean up some of them that's not right, always have the most generic name in the first column, then a specification in second column if present
  mutate(
    first_word = case_when(
      Ingredients == "fruit coctail canned" ~ "coctail",
      Ingredients == "passion fruit" ~ "passion fruit",
      Ingredients == 'white or yellow hard to semi-hard cheese' ~ 'hard to semi-hard cheese',
      Ingredients == 'egg noodle cooked' ~ 'egg noodle',
      Ingredients == 'horse-radish' ~ 'horseradish',
      Ingredients == 'lasagne sheets uncooked' ~ 'lasagna',
      Ingredients == 'pork neck chops' ~ 'neck',
      Ingredients == 'sugar snap peas' ~ 'sugar snap peas',
      Ingredients %in% c('black pepper whole','black pepper grounded') ~ 'pepper',
      Ingredients == 'black chokeberries' ~ 'chokeberries',
      Ingredients == "chick pea dry" ~ "chick pea",
      Ingredients == 'chick pea flour' ~ 'chick pea',
      Ingredients == 'chick pea canned' ~ 'chick pea',
      Ingredients == 'sugar snap pea' ~ 'pea',
      Ingredients == 'smoke-cured ham' ~ 'ham',
      Ingredients == 'cured ham' ~ 'ham',
      Ingredients == 'grilled sweet pepper' ~ 'sweet pepper',
      Ingredients == 'ground meat' ~ 'meat',
      Ingredients == 'bog blueberries' ~ 'bog blueberries',
      Ingredients == 'cured leg of mutton' ~ 'mutton',
      Ingredients == 'whole-grain pasta' ~ 'pasta',
      Ingredients == 'grapess' ~ 'grapes',
      Ingredients == 'soft-ripened cheese (brie camembert etc)' ~ 'soft ripened cheese',
      Ingredients == 'bean white large canned' ~ 'bean white',
      Ingredients == 'bean kidney canned' ~ 'bean kidney',
      Ingredients == 'bean black canned' ~ 'bean black',
      Ingredients == 'cream sauce base' ~ 'cream sauce base',
      Ingredients == 'fish soup base' ~ 'fish soup base',
      Ingredients == 'sausage turkey chicken' ~ 'sausage turkey chicken',
      Ingredients == 'ice cream' ~ 'ice cream',
      Ingredients == 'ice cream cake' ~ 'ice cream',
      Ingredients == 'chicken skewer satay' ~ 'chicken skewer',
      Ingredients == 'tomato sun dried' ~ "tomato",
      Ingredients == 'tomato sun dried in oil' ~ "tomato",
      Ingredients == "cloudberries" ~ "cloud",
      Ingredients == 'lemon balm fresh' ~ 'lemon balm',
      Ingredients == 'oatbran' ~ 'oat bran',
      Ingredients == 'wheatbran' ~ 'wheat bran',
      Ingredients == "potato flatbread lompe" ~ "potato flatbread",
      Ingredients %in% c("pita bread", "pita bread coarse", "pita bread white") ~ "pita bread",
      Ingredients == "soup instant cauliflower" ~ "soup instant",
      Ingredients == "spring roll paper" ~ "spring roll",
      Ingredients == "waffel sour cream" ~ "waffel",
      Ingredients == "beef minced meat" ~ "beef",
      Ingredients == "pork minced meat" ~ "pork",
      Ingredients == "parata flat bread" ~ "parata",
      Ingredients == "chili pepper dried" ~ "chili pepper",
      Ingredients == "pork ham roast" ~ "pork",
      Ingredients == "spice mix meat" ~ "spice mix",
      Ingredients == "milk chocolate non-stop" ~ "milk chocolate",
      Ingredients %in% c("tikka masala paste", "sauce tikka masala") ~ "tikka masala",
      Ingredients == "sausage_pork belly" ~ "sausage",
      Ingredients == "berries mixed wild" ~ "berries",
      Ingredients == "sauce red wine" ~ "sauce",
      Ingredients == "sauce sweet and sour" ~ "sauce",
      Ingredients == "passion fruit curd" ~ "curd",
      Ingredients == "taco dinner kit" ~ "dinner kit",
      Ingredients == "dairy imitate oatmilk full fat" ~ "dairy imitate",
      Ingredients == "fajita spice mix" ~ "spice mix",
      TRUE ~ first_word),

    second_word = case_when(
      Ingredients == "fruit coctail canned" ~ "fruit",
      Ingredients == "passion fruit" ~ '\\',
      Ingredients == 'white or yellow hard to semi-hard cheese' ~ '\\',
      Ingredients == 'chicken with skin' ~ 'whole',
      Ingredients == 'chili pepper red' ~ 'red',
      Ingredients == 'cod traditional Norwegian dish Lutefisk' ~ 'lutefisk',
      str_detect(Ingredients, 'gg noodle') & str_detect(Ingredients, 'cooked') ~ 'cooked',
      str_detect(Ingredients, 'gg noodle') & str_detect(Ingredients, 'uncooked') ~ '\\',
      str_detect(Ingredients, 'capers|kapers') ~ '\\',
      Ingredients == 'lasagne sheets uncooked' ~ 'plate',
      Ingredients == 'oil liquid margarine' ~ '\\',
      Ingredients == 'onion yellow/red' ~ '\\',
      Ingredients == 'pork neck chops' ~ 'chops',
      Ingredients == 'quinoa tørr' ~ '\\',
      Ingredients == 'sugar snap peas' ~ '\\',
      Ingredients == 'mackerel fillet, in tomato sauce, canned' ~ 'tomato',
      Ingredients %in% c('olives black in oil canned', 'oliven, svarte, i olje, hermetisk') ~ 'black',
      Ingredients == 'black pepper whole' ~ 'whole',
      Ingredients == 'black pepper grounded' ~ 'ground',
      Ingredients == 'chick pea dry' ~ '\\',
      Ingredients == 'chick pea flour' ~ 'flour',
      Ingredients == 'chick pea canned' ~ 'canned',
      Ingredients == 'mackerel fillet, in tomato sauce, canned' ~ 'tomato',
      Ingredients == 'smoke-cured ham' ~ 'smoked',
      Ingredients == 'cured ham' ~ 'cured',
      Ingredients == 'grilled sweet pepper' ~ 'grilled',
      Ingredients == 'ground meat' ~ 'ground',
      Ingredients == 'black chokeberries' ~ 'black',
      Ingredients == 'bog blueberries' ~ '\\',
      Ingredients == 'cured leg of mutton' ~ 'cured leg',
      Ingredients == 'lentils dry' ~ '\\',
      Ingredients == 'sugar snap pea' ~ 'sugar snap',
      Ingredients == 'hamburger bun' ~ 'bread',
      Ingredients == 'whole-grain pasta' ~ 'whole grain',
      Ingredients == 'ginger root' ~ '\\',
      Ingredients == 'spinach, raw' ~ '\\',
      Ingredients == 'mushroom common' ~ '\\',
      Ingredients == 'olives black in oil canned' ~ 'black',
      Ingredients == 'bean white large canned' ~ 'canned',
      Ingredients == 'bean white in tomato sauce canned' ~ 'tomato',
      Ingredients == 'bean kidney canned' ~ 'canned',
      Ingredients == 'bean black canned' ~ 'canned',
      Ingredients == 'sausage turkey chicken' ~ '\\',
      Ingredients == 'ice cream' ~ '\\',
      Ingredients == 'chicken skewer satay' ~ 'satay',
      Ingredients == 'egg noodle cooked' ~ 'cooked',
      Ingredients == 'tomato sun dried' ~ "sun dried",
      Ingredients == 'tomato sun dried in oil' ~ "sun dried in oil",
      Ingredients == "cloudberries" ~ "berr",
      Ingredients == 'lemon balm fresh' ~ 'fresh',
      Ingredients == 'oatbran' ~ '\\',
      Ingredients == 'wheatbran' ~ '\\',
      Ingredients == "potato flatbread lompe" ~ "lompe",
      Ingredients == "pita bread" ~ "\\",
      Ingredients == "soup instant cauliflower" ~ "cauliflower",
      Ingredients == "spring roll paper" ~ "paper",
      Ingredients == "waffel sour cream" ~ "sour cream",
      Ingredients == "pita bread coarse" ~ "coarse",
      Ingredients == "pita bread white" ~ "white",
      Ingredients %in% c("beef minced meat", "pork minced meat") ~ "minced meat",
      Ingredients == "parata flat bread" ~ "flat bread",
      Ingredients == "chili pepper dried " ~ "dried",
      Ingredients == "pork ham roast" ~ "ham roast",
      Ingredients == 'ice cream cake' ~ 'cake',
      Ingredients == "spice mix meat" ~ "meat",
      Ingredients == "milk chocolate non-stop" ~ "non-stop",
      Ingredients == "tikka masala paste" ~ "paste",
      Ingredients == "sauce tikka masala" ~ "sauce",
      Ingredients == "sausage_pork belly" ~ "pork belly",
      Ingredients == "berries mixed wild" ~ "mixed wild",
      Ingredients == "sauce red wine" ~ "red wine",
      Ingredients == "sauce sweet and sour" ~ "sweet and sour",
      Ingredients == "passion fruit curd" ~ "passion fruit",
      Ingredients == "taco dinner kit" ~ "taco",
      Ingredients == "dairy imitate oatmilk full fat" ~ "oatmilk full fat",
      Ingredients == "fajita spice mix" ~ "fajita",
      TRUE ~ second_word
    )
  ) %>%
  #Set column order
  select(first_word, second_word, database_ID, language) %>% arrange(first_word, second_word)



#Save
saveRDS(unit_weights_query, "./data-raw/unit_weights_query.Rds")
