---
title: "Visualise nutrients or environmental indicators"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualise nutrients or environmental indicators}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Load libraries
```{r setup, message = FALSE}
library(sustainableNutRients)
library(tidyverse)
```

```{r read-data, message = FALSE, echo = FALSE, warning = FALSE}
# Read the data
data("recipes_oda")
data(composite_ingredients_oda)

#Additional entries to databases
additional_entries <- list(
  
  "volume_weight" = tibble(
    tmp = c("bolognese_vegetarian pcs 370",
            "hummus pcs 165",
            "pizza_dough pcs 210",
            "sauce_pizza pack 400",
            "sauce_pad pcs 150",
            "soup_tomato pcs 530",
            "vanilla_pod pcs 3")
  ) %>% separate(col = tmp, into = c("Ingredients", "unit", "grams_per_unit"), sep = " ") %>%
    mutate(grams_per_unit = as.numeric(grams_per_unit)) %>%
    createNewDatabaseEntry(., "volume_weight"),

  "nutrients" = composite_ingredients_oda %>%
    #Standardise food and unit names and amounts, turn volume to weight and calculate nutrient content
   standardiseFoodList() %>%
    findFoodInDatabase(., "volume_weight") %>%
    calculateWeightOfIngredients() %>%
    findFoodInDatabase(., "nutrients") %>%
    #Calculate nutrients per 100 g as this will be used as additional entries to calculate nutrient content of other recipes
    calculateNutrientContentOfFoodlist(., calculate_nutrients = "per 100 g") %>%
    #Format as new database entries for the nutrients database
    createNewDatabaseEntry(., "nutrients"),

  "environmental_impact" = composite_ingredients_oda %>%
   #Standardise food and unit names and amounts, turn volume to weight and calculate nutrient content
    standardiseFoodList() %>%
    findFoodInDatabase(., "volume_weight") %>%
    calculateWeightOfIngredients() %>%
    findFoodInDatabase(., "sustainability") %>%
    #Calculate nutrients per 100 g as this will be used as additional entries to calculate nutrient content of other recipes
    calculateEnvironmentalImpactOfFoodlist(., calculate_sustainability = "per 100 g") %>%
    #Format as new database entries for the nutrients database
    createNewDatabaseEntry(., "sustainability")
)

#Calculate nutrient content and environmental impact
calculations <- list()
calculations$nutrient_content <- recipes_oda$recipes %>%
  standardiseFoodList() %>%
  #Map to volume_weight database
  findFoodInDatabase(., "volume_weight", additional_entries = additional_entries$volume_weight) %>%
  calculateWeightOfIngredients() %>%
  #Map tp nutrient database,add number of portions and calculate nutrient content per portion
  findFoodInDatabase(., "nutrients", additional_entries = additional_entries$nutrients) %>%
  #Add number of portions
  left_join(., recipes_oda$meta %>% select(recipe_name, number_of_portions) %>% unique()) %>%
  calculateNutrientContentOfFoodlist(., calculate_nutrients = "per portion")

calculations$environmental_impact <- recipes_oda$recipes %>%
  standardiseFoodList() %>%
  #Map to volume_weight database
  findFoodInDatabase(., "volume_weight", additional_entries = additional_entries$volume_weight) %>%
  calculateWeightOfIngredients() %>%
  #Map to SHARP ID, add number of portions and calculate environmental impact per portion
  findFoodInDatabase(., "sustainability", additional_entries = additional_entries$sustainability)%>%
  #Add number of portions
  left_join(., recipes_oda$meta %>% select(recipe_name, number_of_portions) %>% unique()) %>%
  calculateEnvironmentalImpactOfFoodlist(., calculate_sustainability = "per portion")
```

# Data
The data used here are the recipes from oda, with their nutrients calculated per portion.

```{r plots-protein-sources}

```

```{r nutrients-rdi}
nutrient_units <- tibble(
  'nutrient' = c('Vitamin A', 'Retinol', 'Beta-carotene',
                'Vitamin D','Vitamin E', 'Thiamin',
                'Riboflavin','Niacin', 'Vitamin B6',
                'Folate', 'Vitamin B12', 'Vitamin C',
                'Calcium', 'Iron', 'Sodium',
                'Potassium', 'Magnesium', 'Zinc',
                'Selenium', 'Copper', 'Phosphorus',
                'Iodine'),  
  'rdi' = c(700, 700, 8400,
            10, 8, 1.1,
            1.3, 15, 1.2,
            400, 2, 75,
            800, 15, 2300,
            3100, 280, 7,
            50, 0.9, 600,
            150))

test <- nutrient_content %>% mutate(database_ID = case_when(
  Ingredients == 'bean salad' ~ fixFoodMappingError(database = nutrients_additional_ingredients$query_words, 'bean salad')))
```
