#' Weight in grams of different units of foods.
#'
#' A dataset containing the unit weights of multiple units
#'  for more than 500 different items of food. The main source
#'  for this dataset is the 2015 "Weights, measures and portion sizes for foods"
#'  database from the Norwegian Directorate of Health, the University of Oslo
#'  and the Norwegian Food Safety Authority.
#'
#' @format A data frame with 1685 rows and six variables.
#' \describe{
#'   \item{Ingredients}{Ingredient name}
#'   \item{unit_enhet}{The unit of the ingredient}
#'   \item{grams_per_unit}{The weight of the unit of the ingredient in grams}
#'   \item{reference}{The reference from where the weight per unit comes from}
#'   \item{database_ID}{A unique identifier for the ingredient}
#'   \item{language}{The language used for the ingredient and unit names}
#' }
#'
#' @source \url{https://www.matportalen.no/verktoy/kostholdsplanleggeren/maal_vekt_og_porsjonsstorrelser_for_matvarer-1}
"unit_weights"

#' Query words used to search through and map recipe ingredients to unit_weights database.
#'
#' One or two words to map ingredients to unit_weights dataframe
#'
#' @format A dataframe with 989 rows and four variables.
#' \describe{
#'   \item{database_ID}{A unique ID for the ingredient to link it to unit_weight database}
#'   \item{language}{The language used for the ingredient and unit names}
#'   \item{first_word}{Generic ingredient name to identify ingredients}
#'   \item{second_word}{A specifier to go with the generic word, f.ex. type of bean or cut of meat}
#' }
"unit_weights_query"

#' Nutrient database mainly from the 2020 edition of the Norwegian food composition datatable Matvaretabellen.
#'
#' A dataset containing the nutrient content of more than 1000 foods from Matvaretabellen 2020 edition,
#' with Norwegian and English names. Also includes some foods not found in Matvaretabellen from the
#' American food composition datatable from FoodData Central April2021 and for computed composite ingredients.
#'
#' @format A dataframe with 2009 rows and 45 variables.
#' \describe{
#'   \item{database_ID}{The unique identifier used for food items in Matvaretabellen, FoodData Central or generated by user}
#'   \item{from}{Where is the nutrient information from: Matvaretabellen, foodDataCentral, or a composite ingredient made by user}
#' }
#'
#' @source \url{https://www.matportalen.no/verktoy/matvaretabellen/}
#' @source \url{https://fdc.nal.usda.gov/download-datasets.html}
"matvaretabellen2020"

#' Query words used to search through and map recipe ingredients to matvaretabellen2020.
#' One or two words to map ingredients to matvaretabellen2020 dataframe.
#'
#' @format A dataframe with 611 rows and three variables.
#' \describe{
#'   \item{first_word}{Generic ingredient name to identify ingredients}
#'   \item{second_word}{A specifier to go with the generic word, f.ex. type of bean or cut of meat}
#'   \item{database_ID}{The unique identifier used for food items in Matvaretabellen, FoodData Central or generated by user}
#' }
"matvaretabellen2020_query"

#' The environmental impact database SHARP Inicators Database
#'
#' A dataset containing 600 unique foods and their environmental impact in
#' greenhouse gas emission and land use.
#'
#' @format A dataframe with 600 rows and five variables.
#' \describe{
#'   \item{FoodEx2}{A FoodEx2 unique identifier for the food}
#'   \item{L1}{The food group the food contains}
#'   \item{GHGE of 1 kg food as consumed_kgCO2eq}{Greenhouse gas emissions of 1 kg food as consumed, in kilo CO2 equivalents}
#'   \item{Land use of 1 kg food as consumed_m2/yr}{Land used to produce 1 kg of food as consumed, in m2/year}
#'   \item{database_ID}{A unique ID for the food used for internal functions}
#' }
#'
#' @source \url{https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:132158}
"SHARP2018"

#' Query words used to search through and map recipe ingredients to SHARP2018.
#'
#' One or two words to map ingredients to the SHARP2018 dataframe.
#'
#' @format A dataframe with 578 rows and three variables.
#' \describe{
#'   \item{first_word}{Generic ingredient name to identify ingredients}
#'   \item{second_word}{A specifier to go with the generic word, f.ex. type of bean or cut of meat}
#'   \item{database_ID}{A unique ID used to map query words to SHARP2018}
#' }
"SHARP2018_query"

#' A character vector of ingredients that when lacking a unit descriptor in recipe is
#' counted as a piece, ie "3 kiwis" will be interpreted as "3 pieces of kiwi".
#'
#' @format A character vector with 100 ingredient names.
"pcs"

#' A character vector of different unit names to extract from ingredient column.
#'
#' @format A character vector with 33 different unit names.
"type_of_units"

#' 100 recipes scraped from the Norwegian online supermarket Oda.
#'
#' A list of two dataframes, one containing recipes and one containing
#' recipe metadata such as number of portions and how the recipe
#' was categorised by Oda.
#'
#' @format A list with two items
#' * Recipes. A tibble with 935 rows and three columns, containing 100 recipes in total.
#'   - recipe_name. Individual recipe names.
#'   - Ingredients. Column with ingredient names and their amounts.
#'   - ingredient_is_part_of Metadata from Oda showing which part of the recipe the ingredient is from.
#' * meta. A tibble with 654 rows and five columns, containing metadata for the recipes.
#'   - recipe_name. Individual recipe names.
#'   - number_of_portions. Number of portions in the recipe.
#'   - likes. Number of likes the recipe has received.
#'   - categories. Categories of the recipe from Oda.
#'
#' @source \url{https://oda.com/no/recipes}
"recipes_oda"
