#' Standardising ingredients names in a recipe, here various other type of foods.
#' @title standardiseOthers
#'
#' @description Standardise names of various other foods.
#'
#' @param df A dataframe with an Ingredients column, listing each ingredient of the recipe in individual rows, and an Ingredients_standardised column.
#'
#' @return The dataframe with a column with various other foods with standardised names.
#'
#' @export
standardiseOthers <- function(df) {
  df  %>%
    
    #Standardise
    mutate(Ingredients_standardised = case_when(
      str_detect(Ingredients, 'agar') ~ 'agar',
      str_detect(Ingredients, 'agave') & str_detect(Ingredients, 'nectar') ~ 'agave nectar',
      str_detect(Ingredients, 'agave') & str_detect(Ingredients, 'syrup') ~ 'agave syrup',
      str_detect(Ingredients, 'asafoetida powder') ~ 'asafoetida powder',
      
      str_detect(Ingredients, 'baking powder') ~ 'baking powder',
      str_detect(Ingredients, 'baking soda|bicarbonate of soda') ~ 'baking soda',
      str_detect(Ingredients, 'beer') & str_detect(Ingredients, 'dark|amber|christmas') ~ 'beer dark',
      str_detect(Ingredients, 'beer|ale') ~ 'beer',
      str_detect(Ingredients, 'beet') & str_detect(Ingredients, 'pickle') ~ 'beetroot pickled',
      Ingredients == 'black truffle or 2 tbsp s truffle oil' ~ 'black truffle',
      str_detect(Ingredients, 'brandy') ~ 'spirits 40 vol-% alcohol brandy',
      str_detect(Ingredients, 'brine') & !str_detect(Ingredients, 'shrimp') ~ 'water brine',
      str_detect(Ingredients, 'bolognese') & str_detect(Ingredients, 'base') ~ 'bolognese base',
      str_detect(Ingredients, 'bearnaise') & str_detect(Ingredients, 'base') ~ 'bearnaise base',
      str_detect(Ingredients, 'beverage') & str_detect(Ingredients, 'carbonated') & str_detect(Ingredients, 'lemon') & str_detect(Ingredients, 'lime') ~ 'carbonated beverage lemon-lime',
      str_detect(Ingredients, 'browning') & str_detect(Ingredients, 'sauce') ~ 'sauce browning',
      str_detect(Ingredients, 'brown') & str_detect(Ingredients, 'gravy') & str_detect(Ingredients, 'mix') | str_detect(Ingredients, 'gravy') & str_detect(Ingredients, 'powder') ~ 'gravy brown mix',
      
      str_detect(Ingredients, 'caper|hijack') ~ 'caper',
      str_detect(Ingredients, 'caramel') & str_detect(Ingredients, 'sauce') ~ ' sauce caramel',
      str_detect(Ingredients, 'caramel') ~ 'caramel',
      (str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'powder|spice')) | str_detect(Ingredients, 'ground red pepper') ~ 'chili powder',
      str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'sweet') ~ 'sweet chili sauce',
      str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'sauce') ~ 'chili sauce',
      str_detect(Ingredients, 'german') & str_detect(Ingredients, 'cake') & str_detect(Ingredients, 'mix') & str_detect(Ingredients, 'chocolate') ~ 'german chocolate cake mix',
      str_detect(Ingredients, 'instant chocolate pudding mix') ~ 'chocolate pudding mix',
      str_detect(Ingredients, 'package brownie mix') ~ 'brownie mix',
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'milk') & !str_detect(Ingredients, 'candy') ~ 'chocolate milk',
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'semi|dark') ~ 'chocolate semi-sweet',
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'unsweetened') ~ 'chocolate unsweetened',
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'white') ~ 'chocolate white',
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'vermicelli') ~ 'chocolate semi-sweet vermicelli',
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'candy') & str_detect(Ingredients, 'bar') | str_detect(Ingredients, 'chocolatebar') ~ 'chocolate candy bar',
      str_detect(Ingredients, 'chocolate') & !str_detect(Ingredients, 'syrup|icing|kruidnoten') ~ 'chocolate semi-sweet', #Default
      str_detect(Ingredients, 'chocolate') & str_detect(Ingredients, 'icing') ~ 'icing chocolate',
      str_detect(Ingredients, 'chutney') & str_detect(Ingredients, 'mango') ~ 'chutney mango',
      str_detect(Ingredients, 'chutney') & str_detect(Ingredients, 'mint') ~ 'chutney mint',
      str_detect(Ingredients, 'cider') & !str_detect(Ingredients, 'vinegar') ~ 'cider',
      str_detect(Ingredients, 'cocoa') | str_detect(Ingredients, 'cacao') & str_detect(Ingredients, 'powder') ~ 'cocoa powder',
      str_detect(Ingredients, 'cognac') ~ 'spirits 40 vol-% alcohol cognac',
      str_detect(Ingredients, 'color') & str_detect(Ingredients, 'sprinkles') ~ 'sprinkles colored',
      str_detect(Ingredients, 'condensed cream') & str_detect(Ingredients, 'celery') ~ 'condensed cream of celery soup',
      str_detect(Ingredients, 'condensed cream') & str_detect(Ingredients, 'chicken') ~ 'condensed cream of chicken soup',
      str_detect(Ingredients, 'condensed cream') & str_detect(Ingredients, 'mushroom') ~ 'condensed cream of mushroom soup',
      str_detect(Ingredients, 'condensed') & str_detect(Ingredients, 'tomato soup') ~ 'condensed tomato soup',
      str_detect(Ingredients, 'cooking') & str_detect(Ingredients, 'spray') ~ 'cooking spray',
      str_detect(Ingredients, 'cream sauce') & str_detect(Ingredients, 'base') ~ 'cream sauce base',
      str_detect(Ingredients, 'crisps') ~ 'crisps',
      str_detect(Ingredients, 'custard') & str_detect(Ingredients, 'hot') ~ 'custard hot',
      str_detect(Ingredients, 'vanilla') & str_detect(Ingredients, 'custard') ~ 'custard vanilla',
      
      str_detect(Ingredients, 'dark rum') | Ingredients == 'rum' ~ 'spirits 40 vol-% alcohol dark rum',
      str_detect(Ingredients, 'dip mix') ~ 'dip mix',
      
      str_detect(Ingredients, 'espresso') & str_detect(Ingredients, 'bean') & str_detect(Ingredients, 'ground') ~ 'espresso bean coffee ground',
      
      str_detect(Ingredients, 'fish soup') & str_detect(Ingredients, 'base') ~ 'fish soup base',
      
      str_detect(Ingredients, 'gravy') & str_detect(Ingredients, 'beef') ~ 'beef gravy',
      str_detect(Ingredients, 'gravy') ~ 'beef gravy', #Use as default
      str_detect(Ingredients, 'guacamole') ~ 'guacamole',
      
      str_detect(Ingredients, 'harissa') & str_detect(Ingredients, 'mild') ~ 'harissa mild',
      str_detect(Ingredients, 'hollandaise') & str_detect(Ingredients, 'base') ~ 'hollandaise base',
      str_detect(Ingredients, 'honey') & !str_detect(Ingredients, 'mustard') ~ 'honey',
      
      str_detect(Ingredients, 'kirsch') ~ 'spirits 40 vol-% alcohol kirsch',
      str_detect(Ingredients, 'kombu') & str_detect(Ingredients, 'dashi') ~ 'dashi kombu dried kelp',
      
      str_detect(Ingredients, 'madeira') ~ 'madeira fortified wine 15 vol-% alcohol',
      str_detect(Ingredients, 'marsala') ~ 'marsala fortified wine 20 vol-% alcohol',
      str_detect(Ingredients, 'marshmallow') & str_detect(Ingredients, 'cream') ~ 'marshmallow cream',
      str_detect(Ingredients, 'marshmallow') ~ 'marshmallow',
      str_detect(Ingredients, 'mire poix') ~ 'mire poix',
      str_detect(Ingredients, 'miso') & str_detect(Ingredients, 'white') & str_detect(Ingredients, 'paste') ~ 'miso paste white',
      str_detect(Ingredients, 'mustard') & str_detect(Ingredients, 'seed') ~ 'mustard seed',
      str_detect(Ingredients, 'mustard') & str_detect(Ingredients, 'powder') ~ 'mustard powder',
      str_detect(Ingredients, 'mustard') & str_detect(Ingredients, 'whole|grain|coarse') ~ 'mustard whole grain',
      str_detect(Ingredients, 'mustard') & str_detect(Ingredients, 'dijon') ~ 'mustard dijon',
      str_detect(Ingredients, 'mustard') & str_detect(Ingredients, 'honey') ~ 'mustard honey',
      str_detect(Ingredients, 'mustard') & !str_detect(Ingredients, 'cheese') ~ 'mustard',
      
      str_detect(Ingredients, 'mayo') & str_detect(Ingredients, 'vegan') ~ 'mayonnaise vegan',
      str_detect(Ingredients, 'mayo') ~ 'mayonnaise',
      
      str_detect(Ingredients, 'noodle') ~ 'rice noodle', #Default
      str_detect(Ingredients, 'nori') & str_detect(Ingredients, 'flak|seaweed') ~ 'nori seaweed',
      
      str_detect(Ingredients, 'olive paste tapenade') ~ 'olive paste tapenade',
      str_detect(Ingredients, 'dry onion soup mix') ~ 'onion soup mix',
      
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'tomato') ~ 'paste tomato',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'sichuan') & str_detect(Ingredients, 'bean') ~ 'chili bean paste sichuan',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'chili') | str_detect(Ingredients, 'sambal|rose harissa') ~ 'paste chili',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'carrot') ~ 'paste carrot',
      str_detect(Ingredients, 'paste|pasta') & str_detect(Ingredients, 'curry') ~ 'paste curry',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'garlic') ~ 'paste garlic',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'shrimp') ~ 'paste shrimp',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'tomato') & str_detect(Ingredients, 'sun') ~ 'paste tomato sun-dried',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'tomato') ~ 'paste tomato',
      str_detect(Ingredients, 'paste') & str_detect(Ingredients, 'vanilla') & str_detect(Ingredients, 'bean') ~ 'paste vanilla bean',
      str_detect(Ingredients, 'pesto') & str_detect(Ingredients, 'vegan') ~ 'pesto vegan',
      str_detect(Ingredients, 'pesto') ~ 'pesto',
      str_detect(Ingredients, 'pepper') & str_detect(Ingredients, 'white') ~ 'white pepper',
      str_detect(Ingredients, 'pepper') & str_detect(Ingredients, 'cayenne') ~ 'cayenne pepper',
      str_detect(Ingredients, 'pepper|Pepper') & !str_detect(Ingredients, 'chili|white|sweet|cayenne|spice|bell|salad|sauce') & !str_detect(Ingredients, 'salt') ~ 'black pepper',
      str_detect(Ingredients, 'sweet green pickle relish') ~ 'sweet green pickle relish',
      str_detect(Ingredients, 'pickle') & !(str_detect(Ingredients, 'cucumber|ginger|sweet pepper|onion|beet')) | str_detect(Ingredients, 'gherkin') ~ 'cucumber pickled', #Standard
      str_detect(Ingredients, 'pizza filling') ~ 'pizza filling',
      
      str_detect(Ingredients, 'sake') ~ 'sake',
      str_detect(Ingredients, 'salt') & str_detect(Ingredients, 'pepper') & str_detect(Ingredients, 'oil') ~ 'salt and pepper and oil',
      str_detect(Ingredients, 'salt') & str_detect(Ingredients, 'pepper') & str_detect(Ingredients, 'butter') ~ 'salt and pepper and butter',
      str_detect(Ingredients, 'salt') & str_detect(Ingredients, 'pepper') ~ 'salt and pepper',
      str_detect(Ingredients, 'salt') & !str_detect(Ingredients, 'peanut|lamb|pork|anchovy|soy|flesk|cashew') ~ 'salt',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'barbeque|barbecue') ~ 'sauce barbeque',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'bearnaise') ~ 'sauce bearnaise',
      str_detect(Ingredients, 'bearnaise') ~ 'sauce bearnaise',
      str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'hot pepper') ~ 'sauce hot pepper',
      str_detect(Ingredients, 'salsa') & str_detect(Ingredients, 'chunky') ~ 'salsa chunky',
      str_detect(Ingredients, 'salsa') & str_detect(Ingredients, 'tomato') ~ 'salsa tomato',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'cheese') ~ 'sauce cheese',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'sweet') ~ 'sauce sweet chili',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'hot') ~ 'sauce hot chili',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'sour') ~ 'sauce sour chili',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'salt') ~ 'sauce salt chili',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'mild') ~ 'sauce mild chili',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') & str_detect(Ingredients, 'garlic') ~ 'sauce chili garlic',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'chili') ~ 'sauce chili',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'cream') ~ 'sauce cream',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'fish|fisk') ~ 'sauce fish',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'hoisin') ~ 'sauce hoisin',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'horseradish') ~ 'sauce horseradish',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'mint') ~ 'sauce mint',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'teriyaki') ~ 'sauce teriyaki',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'tomat') ~ 'sauce tomato',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'oyster') ~ 'sauce oyster',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'pad thai') ~ 'sauce pad thai',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'piri-piri') ~ 'sauce piri-piri',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'soy') & str_detect(Ingredients, 'sweet') | str_detect(Ingredients, 'ketjap medja') ~ 'sauce sweet soy',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'soy') ~ 'sauce soy',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'taco') ~ 'sauce taco',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'tikka masala') ~ 'sauce tikka masala',
      str_detect(Ingredients, 'sauce|saus') & str_detect(Ingredients, 'white') ~ 'sauce white',
      str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'cranberr') ~ 'sauce cranberry',
      str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'worcestershire') ~ 'sauce worcestershire',
      str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'pasta|spagetti|spaghetti') ~ 'sauce pasta',
      str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'pizza') ~ 'sauce pizza',
      str_detect(Ingredients, 'sauce') & str_detect(Ingredients, 'hot') ~ 'sauce hot',
      str_detect(Ingredients, 'sherry') & !str_detect(Ingredients, 'vinegar') ~ 'sherry fortified wine 15 vol-% alcohol',
      str_detect(Ingredients, 'shortening') & str_detect(Ingredients, 'vegetable') ~ 'shortening vegetable',
      str_detect(Ingredients, 'shortening') ~ 'shortening',
      str_detect(Ingredients, 'sugar') & str_detect(Ingredients, 'brown|castor') ~ 'sugar brown',
      str_detect(Ingredients, 'sugar') & str_detect(Ingredients, 'confect|icing|powder') ~ 'sugar confectioners',
      str_detect(Ingredients, 'sugar') & str_detect(Ingredients, 'vanilla') ~ 'sugar vanilla',
      str_detect(Ingredients, 'sugar') & !str_detect(Ingredients, 'asparagus|pea') ~ 'sugar',
      str_detect(Ingredients, 'syrup|sirup') & str_detect(Ingredients, 'maple') ~ 'syrup maple',
      str_detect(Ingredients, 'syrup') & str_detect(Ingredients, 'chocolate') ~ 'syrup chocolate',
      str_detect(Ingredients, 'syrup') ~ 'syrup',
      
      str_detect(Ingredients, 'tabasco') ~ 'tabasco',
      str_detect(Ingredients, 'toenjang') ~ 'toenjang soybean paste',
      str_detect(Ingredients, 'tofu') ~ 'tofu',
      str_detect(Ingredients, 'toro jegergryte') ~ 'toro jegegryte',
      str_detect(Ingredients, 'toro moussaka') ~ 'toro moussaka',
      
      str_detect(Ingredients, 'vanilla') & str_detect(Ingredients, 'extract') ~ 'vanilla extract',
      str_detect(Ingredients, 'vermouth') ~ 'vermouth fortified wine 15 vol-% alcohol',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'apple|cider') ~ 'vinegar apple cider',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'balsamic') ~ 'vinegar balsamic',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'red wine') ~ 'vinegar red wine',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'rice') ~ 'vinegar rice',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'sherry') ~ 'vinegar sherry',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'white wine') ~ 'vinegar white wine',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'wine') ~ 'vinegar wine',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'brown') ~ 'vinegar brown',
      str_detect(Ingredients, 'vinegar') & str_detect(Ingredients, 'clear|light|5%') ~ 'vinegar',
      str_detect(Ingredients, 'vinegar') ~ 'vinegar',
      str_detect(Ingredients, 'vodka') ~ 'spirits 40 vol-% alcohol vodka',
      
      str_detect(Ingredients, 'water') & !str_detect(Ingredients, 'corn|beef|tuna|coffee|chili|cream|cress|chestnut|melon') ~ 'water',
      str_detect(Ingredients, 'water to the corn') ~ 'water',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'cube|dice') & str_detect(Ingredients, 'vegetable') ~ 'broth cube vegetable',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'cube|dice') & str_detect(Ingredients, 'fish') ~ 'broth cube fish',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'cube|dice') & str_detect(Ingredients, 'beef|meat') ~ 'broth cube beef',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'cube|dice') & str_detect(Ingredients, 'chicken') ~ 'broth cube chicken',
      str_detect(Ingredients, 'stock|broth|bouillon|borth') & str_detect(Ingredients, 'cube|dice') ~ 'broth cube',
      str_detect(Ingredients, 'stock|broth|bouillon|power') & str_detect(Ingredients, 'chicken') ~ 'water broth chicken',
      str_detect(Ingredients, 'stock|broth|bouillon|bouilljon|consomme') & str_detect(Ingredients, 'beef|meat') ~ 'water broth beef',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'shellfish') ~ 'water broth shellfish',
      str_detect(Ingredients, 'stock|broth|bouillon|power') & str_detect(Ingredients, 'game|wild') ~ 'water broth game',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'turkey') ~ 'water broth turkey',
      str_detect(Ingredients, 'stock|broth|bouillon') & str_detect(Ingredients, 'vegetable') ~ 'water broth vegetable',
      str_detect(Ingredients, 'stock|broth|bouillon|power') & str_detect(Ingredients, 'lamb') ~ 'water broth lamb',
      str_detect(Ingredients, 'stock|broth|bouillon|power') & str_detect(Ingredients, 'fish') ~ 'water broth fish',
      str_detect(Ingredients, 'stock|broth|bouillon|frying pan|power') ~ 'water broth',
      str_detect(Ingredients, 'wasabi') ~ 'wasabi',
      str_detect(Ingredients, 'whisky|whiskey') ~ 'whisky spirits 40 vol-% alcohol',
      str_detect(Ingredients, 'wine') & str_detect(Ingredients, 'rice') ~ 'wine rice',
      str_detect(Ingredients, 'wine') & str_detect(Ingredients, 'white') & !str_detect(Ingredients, 'vinegar') ~ 'wine white',
      str_detect(Ingredients, 'wine') & str_detect(Ingredients, 'red|merlot') & !str_detect(Ingredients, 'vinegar') ~ 'wine red',
      str_detect(Ingredients, 'wine') & str_detect(Ingredients, 'port') ~ 'wine port fortified wine 20 vol-% alcohol',
      str_detect(Ingredients, 'mirin japanese sweet wine') ~ 'wine mirin',
      
      str_detect(Ingredients, 'yeast') & str_detect(Ingredients, 'dry|dried') ~ 'yeast dry',
      str_detect(Ingredients, 'yeast') & str_detect(Ingredients, 'nutritional') ~ 'yeast nutritional',
      str_detect(Ingredients, 'yeast') ~ 'yeast',
      str_detect(Ingredients, 'yellow') & str_detect(Ingredients, 'cake') & str_detect(Ingredients, 'mix') ~ 'yellow cake mix',
      
      TRUE ~ Ingredients_standardised))
}

